heat_template_version: 2015-04-30

description: >
  Configure hieradata for Cinder Netapp configuration

resources:
  CinderNetappConfig:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            cinder_netapp_data:
              mapped_data:
                cinder_enable_netapp_backend: {get_param: CinderEnableNetappBackend}
                cinder::backend::netapp::title: {get_param: CinderNetappBackendName}
                cinder::backend::netapp::netapp_login: {get_param: CinderNetappLogin}
                cinder::backend::netapp::netapp_password: {get_param: CinderNetappPassword}
                cinder::backend::netapp::netapp_hostname: {get_param: CinderNetappServerHostname}
                cinder::backend::netapp::netapp_server_port: {get_param: CinderNetappServerPort}
                cinder::backend::netapp::netapp_size_multiplier: {get_param: CinderNetappSizeMultiplier}
                cinder::backend::netapp::netapp_storage_family: {get_param: CinderNetappStorageFamily}
                cinder::backend::netapp::netapp_storage_protocol: {get_param: CinderNetappStorageProtocol}
                cinder::backend::netapp::netapp_transport_type: {get_param: CinderNetappTransportType}
                cinder::backend::netapp::netapp_vfiler: {get_param: CinderNetappVfiler}
                cinder::backend::netapp::netapp_volume_list: {get_param: CinderNetappVolumeList}
                cinder::backend::netapp::netapp_vserver: {get_param: CinderNetappVserver}
                cinder::backend::netapp::netapp_partner_backend_name: {get_param: CinderNetappPartnerBackendName}
                cinder::backend::netapp::nfs_shares: {get_param: CinderNetappNfsShares}
                cinder::backend::netapp::nfs_shares_config: {get_param: CinderNetappNfsSharesConfig}
                cinder::backend::netapp::nfs_mount_options: {get_param: CinderNetappNfsMountOptions}
                cinder::backend::netapp::netapp_copyoffload_tool_path: {get_param: CinderNetappCopyOffloadToolPath}
                cinder::backend::netapp::netapp_controller_ips: {get_param: CinderNetappControllerIps}
                cinder::backend::netapp::netapp_sa_password: {get_param: CinderNetappSaPassword}
                cinder::backend::netapp::netapp_storage_pools: {get_param: CinderNetappStoragePools}
                cinder::backend::netapp::netapp_eseries_host_type: {get_param: CinderNetappEseriesHostType}
                cinder::backend::netapp::netapp_webservice_path: {get_param: CinderNetappWebservicePath}
