HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Tie OpenStack components together'
Parameters:
  TemplateRoot:
    Description: URL Base where all of our templates are available
    Type: String
Resources:
  MySQL:
    Type: AWS::CloudFormation::Stack
    TemplateURL:
      Fn::Join:
        - {Ref: TemplateRoot}
        - mysql.yaml
    Parameters:
      InstanceType: m1.small
      KeyName: default
      MySQLImage: image-mysql
  Keystone:
    Type: AWS::CloudFormation::Stack
    TemplateURL:
      Fn::Join:
        - {Ref: TemplateRoot}
        - keystone.yaml
    Parameters:
      KeyName: default
      KeystoneDSN:
        Fn::Join:
          - 'mysql://keystone:'
          - {Fn::GetAtt: [ MySQL , KeystonePassword ]}
          - '@'
          - {Fn::GetAtt: [ MySQL , MySQLHost ]}
          - '/keystone'
