Description: Nova API,Keystone,Heat Engine and API,Glance,Quantum,Dedicated MySQL
  server,Dedicated RabbitMQ Server
HeatTemplateFormatVersion: '2012-12-12'
Parameters:
  InstanceType:
    Default: baremetal
    Description: Flavor to request when deploying.
    Type: String
  KeyName:
    Default: default
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
  Image:
    Default: undercloud
    Type: String
  PowerUserName:
    Default: stack
    Description: What username to ssh to the virtual power host with.
    Type: String
Resources:
  AccessPolicy:
    Properties:
      AllowedResources:
      - notcompute
    Type: OS::Heat::AccessPolicy
  Key:
    Properties:
      UserName:
        Ref: User
    Type: AWS::IAM::AccessKey
  User:
    Properties:
      Policies:
      - Ref: AccessPolicy
    Type: AWS::IAM::User
  notcompute:
    Metadata:
      OpenStack::Heat::Stack: {}
      Openstack::ImageBuilder::Elements: [ boot-stack, heat-cfntools, heat-localip, quantum-network-node ]
      admin-password: unset
      admin-token: unset
      controller-address: 0.0.0.0
      cinder:
        db: mysql://cinder:unset@localhost/cinder
        volume_size_mb: '5000'
      db-password: unset
      glance:
        db: mysql://glance:unset@localhost/glance
        host: 0.0.0.0
      heat:
        admin_password: unset
        admin_tenant_name: service
        admin_user: heat
        auth_encryption_key: unset___________
        db: mysql://heat:unset@localhost/heat
        heat_watch_server_url: http://0.0.0.0:8003
        metadata_server_url: http://0.0.0.0:8000
        waitcondition_server_url: http://0.0.0.0:8000/v1/waitcondition
        access_key_id:
          Ref: Key
        refresh:
        - resource: notcompute
        secret_key:
          Fn::GetAtt:
          - Key
          - SecretAccessKey
        stack:
          name:
            Ref: AWS::StackName
          region:
            Ref: AWS::Region
      interfaces:
        control: eth2
      keystone:
        db: mysql://keystone:unset@localhost/keystone
        host: 0.0.0.0
      nova:
        compute_driver: libvirt.LibvirtDriver
        db: mysql://nova:unset@localhost/nova
        host: 0.0.0.0
      quantum:
        floatingip_end: 192.0.2.64
        floatingip_range: 192.0.2.0/24
        floatingip_start: 192.0.2.45
        host: 0.0.0.0
        metadata_proxy_shared_secret: unset
        ovs_db: mysql://quantum:unset@localhost/ovs_quantum?charset=utf8
        ovs:
          public_interface: eth0
          fixed_range:
            start: 10.0.0.2
            end: 10.255.255.254
          tenant_network_type: gre
          enable_tunneling: 'True'
          local_ip: 0.0.0.0
      rabbit:
        host: 0.0.0.0
        password: guest
      service-password: unset
    Properties:
      ImageId:
        Ref: Image
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyName
    Type: AWS::EC2::Instance
