HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Heat Engine and API'
Parameters:
  AllowedResources:
    Type: CommaDelimitedList
Resources:
  AccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: {Ref: AllowedResources}
  User:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: AccessPolicy } ]
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
Outputs:
  AccessKeyId:
    Ref: Key
  SecretKey:
    Fn::GetAtt: [ Key, SecretAccessKey ]
