HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Glance'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  GlanceDSN:
    Description: DSN for connecting to glance database
    Type: String
  GlanceImage:
    Type: String
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in keystone.
    Type: String
  TemplateURL:
    Type: String
    Default: https://raw.github.com/openstack-ops/templates/master/
Resources:
  GlanceUser:
    Type: AWS::CloudFormation::Stack
    TemplateURL: {Fn::Join: [ {Ref: TemplateURL} , 'generic-user.yaml' ]}
    Parameters:
      AccessList: [ Glance ]
  Glance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: GlanceImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::ImageBuilder::Elements: [ glance ]
      heat: 
        access_key_id:
          Fn::GetAtt: [ GlanceUser, AccessKeyId ]
        secret_key:
          Fn::GetAtt: [ GlanceUser, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: Glance
      keystone:
        host: {Ref: KeystoneHost}
      glance:
        db: {Ref: GlanceDSN}
      service-password: {Ref: ServicePassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      swift.store_user: ''
      swift.store_key: ''
