HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - Heat Engine and API'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  HeatUser:
    Description: Heat database username.
    Type: String
    Default: heat
  HeatEngineImage:
    Type: String
  HeatApiImage:
    Type: String
  RabbitMQHost:
    Description: Host for RabbitMQ
    Type: String
  RabbitMQPassword:
    Description: Password for RabbitMQ
    Type: String
  ApiGroupSize:
    Description: How many API nodes to run
    Type: Integer
    Default: 1
  AvailabilityZones:
    Type: List
    Default: [ 1 ]
  TemplateURL:
    Type: String
    Default: https://raw.github.com/openstack-ops/templates/master/
Resources:
  EngineUser:
    Type: AWS::CloudFormation::Stack
    TemplateURL: {Fn::Join: [ {Ref: TemplateURL} , 'generic-user.yaml' ]}
    Parameters:
      AccessList: [ HeatEngine ]
  ApiUser:
    Type: AWS::CloudFormation::Stack
    TemplateURL: {Fn::Join: [ {Ref: TemplateURL} , 'generic-user.yaml' ]}
    Parameters:
      AccessList: [ HeatAPI, HeatAPILaunch ]
  HeatAPILaunch:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::ImageBuilder::Elements: [ heat-api ]
      heat:
        rpc_backend: heat.openstack.common.rpc.impl_kombu
        rabbit:
          host: {Ref: RabbitMQHost}
          password: {Ref: RabbitMQPassword}
        access_key_id:
          Fn::GetAtt: [ ApiUser, AccessKeyId ]
        secret_key:
          Fn::GetAtt: [ ApiUser, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: HeatAPILaunch
    Properties:
      ImageId:
        {Ref: HeatApiImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
      UserData: "#!/bin/bash\ntouch /tmp/userdata-finished\necho Userdata finished $(date)\n"
  HeatAPI:
    Type: OS::Heat::InstanceGroup
    Properties:
      LaunchConfiguration: {Ref: HeatApiLaunch}
      Size: {Ref: ApiGroupSize}
      AvailabilityZones: {Ref: AvailabilityZones}
  HeatEngine:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: HeatEngineImage}
    Metadata:
      heat:
        rpc_backend: heat.openstack.common.rpc.impl_kombu
        rabbit:
          host: {Ref: RabbitMQHost}
          password: {Ref: RabbitMQPassword}
        access_key_id:
          Fn::GetAtt: [ EngineUser, AccessKeyId ]
        secret_key:
          Fn::GetAtt: [ EngineUser, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: HeatEngine
