Description: 'Ironic: Bare Metal provisioning, API and Conductor services.'
Resources:
  ironic:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      OpenStack::Role: notcomputeConfig
      ironic:
        db: mysql://ironic:unset@localhost/ironic
        service-password: {Ref: AdminPassword}

