HeatTemplateFormatVersion: '2012-12-12'
Description: 'Nagios3'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    Default: default
  AdmWebPasswd:
    Description: Password for nagiosadmin web admin user.
    Type: String
    Default: nagiosadmin
  NovaHostIp:
    Description: nova ip.
    Type: String
    Default: 192.0.2.1
  NovaOsPassword:
    Description: nova OS_PASSWORD.
    Type: String
    Default: unset
  NovaOsUsername:
    Description: nova OS_USERNAME.
    Type: String
    Default: admin
  NovaOsTenantName:
    Description: nova OS_TENANT_NAME.
    Type: String
    Default: admin
  Nagios3ImageId:
    Description: Nagios image.
    Type: String
    Default: nagios3
  InstanceType:
    Description: Use this flavor.
    Type: String
    Default: baremetal
  InitialIpSplitKey:
    Description: Network name from nova list to get initial ip list from.
    Type: String
    Default: ctlplane
  Apache2SnakeoilPem:
    Description: Snakeoil PEM file.
    Type: String
    Default: |
      -----  BEGIN PlaceHolder...
  Apache2SnakeoilKey:
    Description: Snakeoil Key file.
    Type: String
    Default: |
      -----  BEGIN PlaceHolder...
Resources:
  nagios3:
    Metadata:
      OpenStack::ImageBuilder::Elements: [ nagios3 ]
      apache2:
        snakeoil_pem:
          Ref: Apache2SnakeoilPem
        snakeoil_key:
          Ref: Apache2SnakeoilKey
      nagios3:
        adm_web_passwd:
          Ref: AdmWebPasswd
        nova_host_ip:
          Ref: NovaHostIp
        nova_os_password:
          Ref: NovaOsPassword
        nova_os_username:
          Ref: NovaOsUsername
        nova_os_tenant_name:
          Ref: NovaOsTenantName
        initial_network_split_key:
          Ref: InitialIpSplitKey
    Type: AWS::EC2::Instance
    Properties:
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: Nagios3ImageId
      InstanceType: {Ref: InstanceType}
Outputs:
    Nagios3Host:
        Fn::GetAtt: [ nagios3 , PrivateIp ]