HeatTemplateFormatVersion: '2012-12-12'
Description: 'Nova Compute'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: baremetal
  NovaImage:
    Type: String
    Default: overcloud-compute
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in nova.
    Type: String
  NeutronHost:
    Type: String
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
  NovaInterfaces:
    Type: String
    Default: eth0
  NovaComputeDriver:
    Type: String
    Default: libvirt.LibvirtDriver
  NovaApiHost:
    Type: String
  GlanceHost:
    Type: String
  NovaDSN:
    Type: String
  NeutronDSN:
    Type: String
  NeutronBridgeMappings:
    Type: String
  NeutronNetworkVLANRanges:
    Type: String
  NeutronNetworkType:
    Type: String
  NeutronEnableTunnelling:
    Type: String
Resources:
  AccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: [ NovaCompute ]
  User:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: AccessPolicy } ]
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
  NovaCompute:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: NovaImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::ImageBuilder::Elements: [ nova-compute ]
      heat: 
        access_key_id:
          Ref: Key
        secret_key:
          Fn::GetAtt: [ Key, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: NovaCompute
      nova:
        compute_driver: {Ref: NovaComputeDriver}
        db: {Ref: NovaDSN}
        host: {Ref: NovaApiHost}
      glance:
        host: {Ref: GlanceHost}
      keystone:
        host: {Ref: KeystoneHost}
      neutron:
        host: {Ref: NeutronHost}
        ovs_db: {Ref: NeutronDSN}
        ovs:
          local_ip: 0.0.0.0
          tenant_network_type: {Ref: NeutronNetworkType}
          network_vlan_ranges: {Ref: NeutronNetworkVLANRanges}
          bridge_mappings: {Ref: NeutronBridgeMappings}
          enable_tunneling: {Ref: NeutronEnableTunnelling}

      service-password: {Ref: ServicePassword}
      admin-password: {Ref: ServicePassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      swift:
        store_user: ''
        store_key: ''
      interfaces:
        control: {Ref: NovaInterfaces}
