HeatTemplateFormatVersion: '2012-12-12'
Description: 'Neutron'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  NeutronDSN:
    Description: DSN for connecting to neutron database
    Type: String
  NeutronImage:
    Type: String
  KeystoneHost:
    Type: String
  ServicePassword:
    Description: admin_password for setting up auth in neutron.
    Type: String
  RabbitHost:
    Type: String
  RabbitPassword:
    Type: String
  NeutronInterfaces:
    Type: String
    Default: eth0
Resources:
  AccessPolicy:
    Type: OS::Heat::AccessPolicy
    Properties:
      AllowedResources: [ Neutron ]
  User:
    Type: AWS::IAM::User
    Properties:
      Policies: [ { Ref: AccessPolicy } ]
  Key:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName:
        Ref: User
  Neutron:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        {Ref: NeutronImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      OpenStack::Role: networking
      OpenStack::ImageBuilder::Elements: [ neutron ]
      heat: 
        access_key_id:
          Ref: Key
        secret_key:
          Fn::GetAtt: [ Key, SecretAccessKey ]
        stack:
          name: {Ref: 'AWS::StackName'}
          region: {Ref: 'AWS::Region'}
        refresh:
          - resource: Neutron
      keystone:
        host: {Ref: KeystoneHost}
      neutron:
        ovs_db: {Ref: NeutronDSN}
      service-password: {Ref: ServicePassword}
      admin-password: {Ref: ServicePassword}
      rabbit:
        host: {Ref: RabbitHost}
        password: {Ref: RabbitPassword}
      swift:
        store_user: ''
        store_key: ''
      interfaces:
        control: {Ref: NeutronInterfaces}
