Description: 'ssl-source: SSL endpoint metadata for openstack'
Parameters:
  SSLCertificate:
    Default: ''
    Description: If set, the contents of an SSL certificate .crt file for encrypting SSL endpoints.
    Type: String
    NoEcho: true
  SSLKey:
    Default: ''
    Description: If set, the contents of an SSL certificate .key file for encrypting SSL endpoints.
    Type: String
    NoEcho: true
Resources:
  controller0Config:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      stunnel:
        cert:
          Ref: SSLCertificate
        key:
          Ref: SSLKey
        ports:
         - name: 'ec2'
           accept: 13773
           connect: 8773
         - name: 'image'
           accept: 13292
           connect: 9292
         - name: 'identity'
           accept: 13000
           connect: 5000
         - name: 'network'
           accept: 13696
           connect: 9696
         - name: 'compute'
           accept: 13774
           connect: 8774
         - name: 'swift-proxy'
           accept: 13080
           connect: 8080
         - name: 'cinder'
           accept: 13776
           connect: 8776
