Parameters:
  NeutronPublicInterface:
    Default: eth0
    Description: What interface to bridge onto br-ex for network nodes.
    Type: String
Resources:
  undercloudConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Metadata:
      nova:
        compute_hostname: undercloud
        compute_driver: ironic.driver.IronicDriver
        db: mysql://nova:unset@localhost/nova
        default_ephemeral_format: ext4
        host: 127.0.0.1
        metadata-proxy: false
        tuning:
          ram_allocation_ratio: 1.0
          reserved_host_memory_mb: 0
        service-password:
          Ref: NovaPassword
