heat_template_version: 2016-04-08

description: >
  OpenStack Ceilometer API service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  CeilometerServiceBase:
    type: ../ceilometer-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Ceilometer API pacemaker role.
    value:
      service_name: ceilometer-api
      config_settings:
        map_merge:
          - get_attr: [CeilometerServiceBase, role_data, config_settings]
          - ceilometer::api::manage_service: false
            ceilometer::api::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::ceilometer::api
