heat_template_version: 2016-04-08

description: >
  Openstack Heat API service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  MysqlVirtualIPUri:
    type: string
    default: ''

resources:
  HeatApiBase:
    type: ../heat-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      MysqlVirtualIPUri: {get_param: MysqlVirtualIPUri}

outputs:
  role_data:
    description: Role data for the Heat API role.
    value:
      config_settings:
        map_merge:
          - get_attr: [HeatApiBase, role_data, config_settings]
          - heat::api::manage_service: false
            heat::api::enabled: false
      step_config: |
        include ::tripleo::profile::pacemaker::heat
