heat_template_version: 2016-04-08

description: >
  The manila-share service with Pacemaker configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  ManilaShareBase:
    type: ../manila-share.yaml

outputs:
  role_data:
    description: Role data for the manila-share pacemaker role.
    value:
      service_name: manila_share
      config_settings:
        map_merge:
          - get_attr: [ManilaShareBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::pacemaker::manila
