heat_template_version: 2015-04-30
description: 'Ceph Cluster config data for Puppet'

parameters:
  NovaRbdPoolName:
    default: vms
    type: string
  CephClientUserName:
    default: openstack
    type: string

resources:
  CephClusterConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        hiera:
          datafiles:
            ceph_cluster:
              mapped_data:
                nova::compute::rbd::libvirt_images_rbd_pool: {get_param: NovaRbdPoolName}
                nova::compute::rbd::libvirt_rbd_user: {get_param: CephClientUserName}
                nova::compute::rbd::rbd_keyring:
                  list_join:
                  - '.'
                  - - 'client'
                    - {get_param: CephClientUserName}

outputs:
  config_id:
    description: The ID of the CephClusterConfigImpl resource.
    value:
      {get_resource: CephClusterConfigImpl}
