heat_template_version: 2014-10-16

description: >
  OpenStack controller node post deployment for Puppet.

parameters:
  servers:
    type: json

resources:

  ControllerPuppetConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      options:
        enable_hiera: True
        enable_facter: False
      outputs:
      - name: result
      config:
        get_file: manifests/overcloud_controller.pp

  # Step through a series of Puppet runs using the same manifest.
  # NOTE(dprince): Heat breakpoints would make for a really cool way to step
  # through breakpoints in a controlled manner across the entire cluster
  ControllerPuppetDeploymentLoadBalancer:
    type: OS::Heat::StructuredDeployments
    properties:
      name: puppet_1
      servers:  {get_param: servers}
      config: {get_resource: ControllerPuppetConfig}
      input_values:
        step: 1
      actions: ['CREATE'] # no need for two passes on an UPDATE

  ControllerPuppetDeploymentServicesBase:
    type: OS::Heat::StructuredDeployments
    properties:
      name: puppet_2
      servers:  {get_param: servers}
      config: {get_resource: ControllerPuppetConfig}
      input_values:
        step: 2
      actions: ['CREATE'] # no need for two passes on an UPDATE

  ControllerRingbuilderPuppetConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      options:
        enable_hiera: True
        enable_facter: False
      inputs:
      outputs:
      - name: result
      config:
        get_file: manifests/ringbuilder.pp

  ControllerRingbuilderPuppetDeployment:
    type: OS::Heat::StructuredDeployments
    properties:
      name: puppet_3
      servers:  {get_param: servers}
      config: {get_resource: ControllerRingbuilderPuppetConfig}

  ControllerPuppetDeploymentOvercloudServices:
    type: OS::Heat::StructuredDeployments
    properties:
      name: puppet_4
      servers:  {get_param: servers}
      config: {get_resource: ControllerPuppetConfig}
      input_values:
        step: 3
