# A Heat environment file which can be used to enable a
# a Cinder NetApp backend.
resource_registry:
  OS::TripleO::Controller::CinderBackend: extraconfig/controller/cinder-netapp.yaml

parameter_defaults:
  CinderBackendConfig:
    CinderEnableNetappBackend: false
    CinderNetappBackendName: 'tripleo_netapp'
    CinderNetappLogin: ''
    CinderNetappPassword: ''
    CinderNetappServerHostname: ''
    CinderNetappServerPort: '80'
    CinderNetappSizeMultiplier: '1.2'
    CinderNetappStorageFamily: 'ontap_cluster'
    CinderNetappStorageProtocol: 'nfs'
    CinderNetappTransportType: 'http'
    CinderNetappVfiler: ''
    CinderNetappVolumeList: ''
    CinderNetappVserver: ''
    CinderNetappPartnerBackendName: ''
    CinderNetappNfsShares: ''
    CinderNetappNfsSharesConfig: '/etc/cinder/shares.conf'
    CinderNetappNfsMountOptions: ''
    CinderNetappCopyOffloadToolPath: ''
    CinderNetappControllerIps: ''
    CinderNetappSaPassword: ''
    CinderNetappStoragePools: ''
    CinderNetappEseriesHostType: 'linux_dm_mp'
    CinderNetappWebservicePath: '/devmgr/v2'
