heat_template_version: 2016-04-08

description: >
  MySQL service deployment using puppet

parameters:
  #Parameters not used EndpointMap
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Service MySQL using composable services.
    value:
      config_settings:
      step_config: |
        include ::tripleo::profile::base::database::mysql
