heat_template_version: 2016-04-08

description: >
  OpenStack Redis service configured with Puppet

parameters:
  RedisPassword:
    description: The password for Redis
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the redis role.
    value:
      service_name: redis_base
      config_settings:
        redis::requirepass: {get_param: RedisPassword}
        redis::masterauth: {get_param: RedisPassword}
        redis::sentinel_auth_pass: {get_param: RedisPassword}
        redis::port: 6379
        redis::sentinel::master_name: '"%{hiera(\"bootstrap_nodeid\")}"'
        redis::sentinel::redis_host: '"%{hiera(\"bootstrap_nodeid_ip\")}"'
        redis::sentinel::notification_script: '/usr/local/bin/redis-notifications.sh'
        tripleo::loadbalancer::redis_password: {get_param: RedisPassword}
