heat_template_version: 2015-04-30

description: >
  Storage management network. Storage replication, etc.

parameters:
  # the defaults here work for static IP assignment (IPAM) only
  StorageMgmtNetCidr:
    # OpenStack uses the EUI-64 address format, which requires a /64 prefix
    default: 'fd00:fd00:fd00:4000::/64'
    description: Cidr for the storage management network.
    type: string
  StorageMgmtNetValueSpecs:
    default: {'provider:physical_network': 'storage_mgmt', 'provider:network_type': 'flat'}
    description: Value specs for the storage_mgmt network.
    type: json
  StorageMgmtNetAdminStateUp:
    default: false
    description: This admin state of of the network.
    type: boolean
  StorageMgmtNetShared:
    default: false
    description: Whether this network is shared across all tenants.
    type: boolean
  StorageMgmtNetName:
    default: storage_mgmt
    description: The name of the Storage management network.
    type: string
  StorageMgmtSubnetName:
    default: storage_mgmt_subnet
    description: The name of the Storage management subnet in Neutron.
    type: string
  StorageMgmtAllocationPools:
    default: [{'start': 'fd00:fd00:fd00:4000::10', 'end': 'fd00:fd00:fd00:4000:ffff:ffff:ffff:fffe'}]
    description: Ip allocation pool range for the storage mgmt network.
    type: json

resources:
  StorageMgmtNetwork:
    type: OS::Neutron::Net
    properties:
      admin_state_up: {get_param: StorageMgmtNetAdminStateUp}
      name: {get_param: StorageMgmtNetName}
      shared: {get_param: StorageMgmtNetShared}
      value_specs: {get_param: StorageMgmtNetValueSpecs}

  StorageMgmtSubnet:
    type: OS::Neutron::Subnet
    properties:
      ip_version: 6
      ipv6_address_mode: slaac
      ipv6_ra_mode: slaac
      cidr: {get_param: StorageMgmtNetCidr}
      name: {get_param: StorageMgmtSubnetName}
      network: {get_resource: StorageMgmtNetwork}
      allocation_pools: {get_param: StorageMgmtAllocationPools}

outputs:
  OS::stack_id:
    description: Neutron storage management network
    value: {get_resource: StorageMgmtNetwork}
