heat_template_version: pike

description: >
  OpenStack containerized Glance API service

parameters:
  DockerGlanceApiImage:
    description: image
    type: string

outputs:
  config_settings:
    description: The volumes needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      # Kolla_bootstrap/db_sync runs before permissions set by kolla_config
      step_2:
        glance_init_logs:
          image: {get_param: DockerGlanceApiImage}
          privileged: false
          user: root
          volumes:
            - /var/log/containers/glance:/var/log/glance
            - /var/log/containers/httpd/glance-api:/var/log/httpd
          command: ['/bin/bash', '-c', 'chown -R glance:glance /var/log/glance']
  volumes:
    description: extra volumes
    value:
      - /var/log/containers/glance:/var/log/glance
      - /var/log/containers/httpd/glance-api:/var/log/httpd
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /var/log/containers/glance
          - /var/log/containers/httpd/glance-api
