heat_template_version: pike

description: >
  OpenStack containerized Heat API service

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_2: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/heat:/var/log/heat
      - /var/log/containers/httpd/heat-api:/var/log/httpd
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /var/log/containers/heat
          - /var/log/containers/httpd/heat-api
