heat_template_version: pike

description: >
  OpenStack containerized Keystone service

parameters:
  DockerKeystoneImage:
    description: image
    type: string

outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/keystone:/var/log/keystone
      - /var/log/containers/httpd/keystone:/var/log/httpd
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /var/log/containers/keystone
          - /var/log/containers/httpd/keystone
