heat_template_version: 2016-04-08

description: >
  MySQL with Pacemaker service deployment using puppet

parameters:
  #Parameters not used EndpointMap
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

outputs:
  role_data:
    description: Service MySQL with Pacemaker using composable services.
    value:
      service_name: mysql
      config_settings:
      step_config: |
        include ::tripleo::profile::pacemaker::database::mysql
