description: examples/source2_hot.yaml
heat_template_version: '2013-05-23'
parameters:
  BImage:
    type: string
  ImportantValue:
    default: a_default
    type: string
resources:
  GenericB:
    metadata:
      my_meta: Foo
    properties:
      image:
        get_param: BImage
    type: OS::Nova::Server
