heat_template_version: 2016-04-08

description: >
  OpenStack Ceilometer Central Agent service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  RedisPassword:
    description: The password for the redis service account.
    type: string
    hidden: true
  RedisVirtualIPUri:
    type: string
    default: ''


resources:
  CeilometerServiceBase:
    type: ./ceilometer-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Ceilometer Central Agent role.
    value:
      service_name: ceilometer-agent-central
      config_settings:
        map_merge:
          - get_attr: [CeilometerServiceBase, role_data, config_settings]
          - ceilometer::agent::central::coordination_url:
              list_join:
                - ''
                - - 'redis://:'
                  - {get_param: RedisPassword}
                  - '@'
                  - {get_param: RedisVirtualIPUri}
                  - ':6379/'
      step_config: |
        include ::tripleo::profile::base::ceilometer::agent::central
