heat_template_version: 2016-04-08

description: >
  Gnocchi service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  GnocchiServiceBase:
    type: ./gnocchi-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Gnocchi role.
    value:
      config_settings:
        map_merge:
          - get_attr: [GnocchiServiceBase, role_data, config_settings]
      step_config: |
        include ::tripleo::profile::base::gnocchi::api
