heat_template_version: 2016-04-08

description: >
  Gnocchi service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  GnocchiPassword:
    description: The password for the gnocchi service and db account.
    type: string
    hidden: true
  KeystoneRegion:
    type: string
    default: 'regionOne'
    description: Keystone region for endpoint

resources:
  GnocchiServiceBase:
    type: ./gnocchi-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Gnocchi role.
    value:
      service_name: gnocchi_api
      config_settings:
        map_merge:
          - get_attr: [GnocchiServiceBase, role_data, config_settings]
          - tripleo.gnocchi_api.firewall_rules:
              '129 gnocchi-api':
                dport:
                  - 8041
                  - 13041
            gnocchi::api::keystone_tenant: 'service'
            gnocchi::keystone::auth::tenant: 'service'
            gnocchi::keystone::auth::region: {get_param: KeystoneRegion}
            gnocchi::keystone::auth::password: {get_param: GnocchiPassword}
            gnocchi::keystone::auth::public_url: { get_param: [ EndpointMap, GnocchiPublic, uri ] }
            gnocchi::keystone::auth::internal_url: {get_param: [EndpointMap, GnocchiInternal, uri]}
            gnocchi::keystone::auth::admin_url: { get_param: [ EndpointMap, GnocchiAdmin, uri ] }
      step_config: |
        include ::tripleo::profile::base::gnocchi::api
