heat_template_version: 2016-04-08

description: >
  Manila-share service configured with Puppet

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:
  ManilaBase:
    type: ./manila-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}

outputs:
  role_data:
    description: Role data for the Manila-share role.
    value:
      service_name: manila_share
      config_settings:
        map_merge:
          - get_attr: [ManilaBase, role_data, config_settings]
          - manila::volume::cinder::cinder_admin_tenant_name: 'service'
      step_config: |
        include ::tripleo::profile::base::manila::share
