heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Plumgrid plugin

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  NeutronPassword:
    description: The password for the neutron service and db account, used by neutron agents.
    type: string
    hidden: true
  NeutronMetadataProxySharedSecret:
    description: Shared secret to prevent spoofing
    type: string
    hidden: true
  AdminPassword:
    description: The password for the keystone admin account, used for monitoring, querying neutron etc.
    type: string
    hidden: true

outputs:
  role_data:
    description: Role data for the Neutron Plumgrid plugin
    value:
      config_settings:
        neutron::plugins::plumgrid::connection:
          list_join:
            - ''
            - - {get_param: [EndpointMap, MysqlInternal, protocol]}
              - '://neutron:'
              - {get_param: NeutronPassword}
              - '@'
              - {get_param: [EndpointMap, MysqlInternal, host]}
              - '/ovs_neutron?charset=utf8'
        neutron::plugins::plumgrid::controller_priv_host: {get_param: [EndpointMap, KeystoneAdmin, host]}
        neutron::plugins::plumgrid::admin_password: {get_param: AdminPassword}
        neutron::plugins::plumgrid::metadata_proxy_shared_secret: {get_param: NeutronMetadataProxySharedSecret}
      step_config: |
        include tripleo::profile::base::neutron::plugins::plumgrid
