heat_template_version: 2016-04-08

description: >
  OpenStack Neutron Opencontrail plugin

parameters:
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json

resources:

  NeutronBase:
    type: ./neutron-base.yaml

outputs:
  role_data:
    description: Role data for the Neutron Opencontrail plugin
    value:
      config_settings:
        map_merge:
          - get_attr: [NeutronBase, role_data, config_settings]
      step_config: |
        include tripleo::profile::base::neutron::plugins::opencontrail
