# Nova
nova::db::mysql::user: nova
nova::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
nova::db::mysql::dbname: nova
nova::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

nova::db::mysql_api::user: nova_api
nova::db::mysql_api::host: "%{hiera('mysql_virtual_ip')}"
nova::db::mysql_api::dbname: nova_api
nova::db::mysql_api::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Ceilometer
ceilometer::db::mysql::user: ceilometer
ceilometer::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
ceilometer::db::mysql::dbname: ceilometer
ceilometer::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"

# Aodh
aodh::db::mysql::user: aodh
aodh::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
aodh::db::mysql::dbname: aodh
aodh::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"
