# Aodh
# TODO(emilien) move it to composable aodh roles later
aodh::db::mysql::user: aodh
aodh::db::mysql::host: "%{hiera('mysql_virtual_ip')}"
aodh::db::mysql::dbname: aodh
aodh::db::mysql::allowed_hosts:
  - '%'
  - "%{hiera('mysql_bind_host')}"
