heat_template_version: 2014-10-16
description: 'Upgrade for Pacemaker deployments'

parameters:
  servers:
    type: json
  input_values:
    type: json
    description: input values for the software deployments

resources:
  ControllerPacemakerUpgradeConfig_Step1:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        list_join:
        - ''
        - - get_file: pacemaker_common_functions.sh
          - get_file: major_upgrade_pacemaker_1.sh

  ControllerPacemakerUpgradeDeployment_Step1:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerPacemakerUpgradeConfig_Step1}
      input_values: {get_param: input_values}

  ControllerPacemakerUpgradeConfig_Step2:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        list_join:
        - ''
        - - get_file: pacemaker_common_functions.sh
          - get_file: major_upgrade_pacemaker_2.sh

  ControllerPacemakerUpgrade2Deployment_Step2:
    type: OS::Heat::SoftwareDeploymentGroup
    depends_on: ControllerPacemakerUpgradeDeployment_Step1
    properties:
      servers:  {get_param: servers}
      config: {get_resource: ControllerPacemakerUpgradeConfig_Step2}
      input_values: {get_param: input_values}
