heat_template_version: ocata

description: >
  OpenStack containerized aodh service

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerAodhApiImage:
    description: image
    default: 'centos-binary-aodh-api:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  AodhApiPuppetBase:
      type: ../../puppet/services/aodh-api.yaml
      properties:
        EndpointMap: {get_param: EndpointMap}
        ServiceNetMap: {get_param: ServiceNetMap}
        DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the aodh API role.
    value:
      service_name: {get_attr: [AodhApiPuppetBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [AodhApiPuppetBase, role_data, config_settings]
          - apache::default_vhost: false
      step_config: &step_config
        get_attr: [AodhApiPuppetBase, role_data, step_config]
      service_config_settings: {get_attr: [AodhApiPuppetBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS
      puppet_config:
        config_volume: aodh
        puppet_tags: aodh_api_paste_ini,aodh_config
        step_config: *step_config
        config_image: &aodh_image
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerAodhApiImage} ]
      kolla_config:
          /var/lib/kolla/config_files/aodh-api.json:
           command: /usr/sbin/httpd -DFOREGROUND
           config_files:
           - dest: /etc/aodh/aodh.conf
             owner: aodh
             perm: '0640'
             source: /var/lib/kolla/config_files/src/etc/aodh/aodh.conf
           - dest: /etc/httpd/conf.d/10-aodh_wsgi.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf.d/10-aodh_wsgi.conf
           - dest: /etc/httpd/conf/httpd.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf/httpd.conf
           - dest: /etc/httpd/conf/ports.conf
             owner: root
             perm: '0644'
             source: /var/lib/kolla/config_files/src/etc/httpd/conf/ports.conf
           - dest: /var/www/cgi-bin/aodh/app
             owner: aodh
             perm: '0644'
             source: /var/lib/kolla/config_files/src/var/www/cgi-bin/aodh/app
      docker_config:
        step_3:
          aodh-init-log:
            start_order: 0
            image: *aodh_image
            user: root
            command: ['/bin/bash', '-c', 'mkdir -p /var/log/httpd && mkdir -p /var/log/aodh && chown aodh:aodh /var/log/aodh']
            volumes:
              - logs:/var/log
          aodh_db_sync:
            start_order: 1
            image: *aodh_image
            net: host
            privileged: false
            detach: false
            volumes:
              - /var/lib/config-data/aodh/etc/aodh/:/etc/aodh:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              - logs:/var/log
            command: /usr/bin/aodh-dbsync
        step_4:
          aodh-api:
            image: *aodh_image
            net: host
            privileged: false
            restart: always
            volumes:
              - /var/lib/kolla/config_files/aodh-api.json:/var/lib/kolla/config_files/config.json:ro
              - /var/lib/config-data/aodh/:/var/lib/kolla/config_files/src:ro
              - /var/lib/config-data/aodh/etc/httpd/conf.modules.d:/etc/httpd/conf.modules.d:ro
              - /etc/hosts:/etc/hosts:ro
              - /etc/localtime:/etc/localtime:ro
              - logs:/var/log
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
