heat_template_version: ocata

description: >
  Contains a static list of common things necessary for containers

outputs:
  volumes:
    description: Common volumes for the containers.
    value:
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
