heat_template_version: pike

description: >
  OpenStack Glance service configured with Puppet

parameters:
  DockerNamespace:
    description: namespace
    default: 'tripleoupstream'
    type: string
  DockerGlanceApiImage:
    description: image
    default: 'centos-binary-glance-api:latest'
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json

resources:

  ContainersCommon:
    type: ./containers-common.yaml

  GlanceApiPuppetBase:
    type: ../../puppet/services/glance-api.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}

outputs:
  role_data:
    description: Role data for the Glance API role.
    value:
      service_name: {get_attr: [GlanceApiPuppetBase, role_data, service_name]}
      config_settings:
        map_merge:
          - get_attr: [GlanceApiPuppetBase, role_data, config_settings]
          - glance::api::sync_db: false
      step_config: &step_config
        get_attr: [GlanceApiPuppetBase, role_data, step_config]
      service_config_settings: {get_attr: [GlanceApiPuppetBase, role_data, service_config_settings]}
      # BEGIN DOCKER SETTINGS #
      puppet_config:
        config_volume: glance_api
        puppet_tags: glance_api_config,glance_api_paste_ini,glance_swift_config,glance_cache_config
        step_config: *step_config
        config_image: &glance_image
          list_join:
            - '/'
            - [ {get_param: DockerNamespace}, {get_param: DockerGlanceApiImage} ]
      kolla_config:
        /var/lib/kolla/config_files/glance-api.json:
          command: /usr/bin/glance-api --config-file /usr/share/glance/glance-api-dist.conf --config-file /etc/glance/glance-api.conf
      docker_config:
        # Kolla_bootstrap/db_sync runs before permissions set by kolla_config
        step_3:
          glance_init_logs:
            start_order: 0
            image: *glance_image
            privileged: false
            user: root
            volumes:
              - /var/log/containers/glance:/var/log/glance
            command: ['/bin/bash', '-c', 'chown -R glance:glance /var/log/glance']
          glance_api_db_sync:
            start_order: 1
            image: *glance_image
            net: host
            privileged: false
            detach: false
            volumes: &glance_volumes
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                -
                  - /var/lib/kolla/config_files/glance-api.json:/var/lib/kolla/config_files/config.json
                  - /var/lib/config-data/glance_api/etc/glance/:/etc/glance/:ro
                  - /var/log/containers/glance:/var/log/glance
            environment:
              - KOLLA_BOOTSTRAP=True
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
        step_4:
          glance_api:
            start_order: 2
            image: *glance_image
            net: host
            privileged: false
            restart: always
            volumes: *glance_volumes
            environment:
              - KOLLA_CONFIG_STRATEGY=COPY_ALWAYS
      host_prep_tasks:
        - name: create persistent logs directory
          file:
            path: /var/log/containers/glance
            state: directory
      upgrade_tasks:
        - name: Stop and disable glance_api service
          tags: step2
          service: name=openstack-glance-api state=stopped enabled=no
